name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      CMAKE_BUILD_PARALLEL_LEVEL: 4

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain & deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build python3 python3-pip dos2unix libgtest-dev

      
      - name: Build & install GoogleTest
        run: |
          sudo cmake -S /usr/src/googletest -B /usr/src/googletest/build -G Ninja -DCMAKE_BUILD_TYPE=Release
          sudo cmake --build /usr/src/googletest/build --target install

      - name: Configure (Release)
        run: cmake -S . -B build-release -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build (Release)
        run: cmake --build build-release --verbose

      - name: Run unit tests (Release)
        run: ctest --test-dir build-release --output-on-failure

      
      - name: Configure (Debug, ASan/UBSan)
        run: cmake -S . -B build-debug -G Ninja -DCMAKE_BUILD_TYPE=Debug

      - name: Build (Debug)
        run: cmake --build build-debug --verbose

      - name: Run unit tests (Debug, ASan/UBSan)
        run: ctest --test-dir build-debug --output-on-failure

      
      - name: Prepare E2E script
        run: |
          dos2unix tests/e2e/end_to_end_test.sh || true
          chmod +x tests/e2e/end_to_end_test.sh

      - name: Run E2E tests (use Release binary)
        working-directory: tests/e2e
        shell: bash
        env:
          MATRIX_BIN: ${{ github.workspace }}/build-release/matrix
        run: |
          # если скрипт ожидает бинарник в build/, а не в переменной — можно экспортировать/подменить путь тут
          ./end_to_end_test.sh
